// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.
// Run `go generate ./...` to regenerate.

package model

type {{ EntityName }} struct {
	ID          string `json:"id"`
	DisplayName string `json:"displayName"`
}
